[package]
name = "el_obs"
version = "0.1.0"
edition = "2021"

[dependencies]
el_core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
