[package]
name = "strategy_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
el_core = { path = "../core" }
d2 = { path = "../d2" }
