[package]
name = "exec-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
el_core = { path = "../core" }
exec = { path = "../exec" }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
