[package]
name = "risk"
version = "0.1.0"
edition = "2024"

[dependencies]
el_contracts = { path = "../el_contracts" }
el_core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
