[package]
name = "execution-bridge"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
el_core = { path = "../el_core" }
el_eventlog = { path = "../eventlog" }
serde = { version = "1", features = ["derive"] }
anyhow = "1"

