[package]
name = "replay"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
el_core = { path = "../core" }
eventlog = { path = "../eventlog" }
orderbook = { path = "../orderbook" }

anyhow = "1"
blake3 = "1"
serde_json = "1"
uuid = "1"
